apiVersion: v1
kind: Service
metadata:
  name: sovereign-service
  namespace: default
spec:
  selector:
    app: sovereign
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP
