// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: internal/mesh/gossip.proto

package mesh

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GossipMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp      int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SummaryHash    []byte                 `protobuf:"bytes,3,opt,name=summary_hash,json=summaryHash,proto3" json:"summary_hash,omitempty"`
	SummaryPayload []byte                 `protobuf:"bytes,4,opt,name=summary_payload,json=summaryPayload,proto3" json:"summary_payload,omitempty"`
	Signature      []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GossipMessage) Reset() {
	*x = GossipMessage{}
	mi := &file_internal_mesh_gossip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipMessage) ProtoMessage() {}

func (x *GossipMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_mesh_gossip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipMessage.ProtoReflect.Descriptor instead.
func (*GossipMessage) Descriptor() ([]byte, []int) {
	return file_internal_mesh_gossip_proto_rawDescGZIP(), []int{0}
}

func (x *GossipMessage) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GossipMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GossipMessage) GetSummaryHash() []byte {
	if x != nil {
		return x.SummaryHash
	}
	return nil
}

func (x *GossipMessage) GetSummaryPayload() []byte {
	if x != nil {
		return x.SummaryPayload
	}
	return nil
}

func (x *GossipMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_internal_mesh_gossip_proto protoreflect.FileDescriptor

const file_internal_mesh_gossip_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/mesh/gossip.proto\x12\x04mesh\"\xb0\x01\n" +
	"\rGossipMessage\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12!\n" +
	"\fsummary_hash\x18\x03 \x01(\fR\vsummaryHash\x12'\n" +
	"\x0fsummary_payload\x18\x04 \x01(\fR\x0esummaryPayload\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignatureB*Z(github.com/Sachin0Amit/new/internal/meshb\x06proto3"

var (
	file_internal_mesh_gossip_proto_rawDescOnce sync.Once
	file_internal_mesh_gossip_proto_rawDescData []byte
)

func file_internal_mesh_gossip_proto_rawDescGZIP() []byte {
	file_internal_mesh_gossip_proto_rawDescOnce.Do(func() {
		file_internal_mesh_gossip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_mesh_gossip_proto_rawDesc), len(file_internal_mesh_gossip_proto_rawDesc)))
	})
	return file_internal_mesh_gossip_proto_rawDescData
}

var file_internal_mesh_gossip_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_mesh_gossip_proto_goTypes = []any{
	(*GossipMessage)(nil), // 0: mesh.GossipMessage
}
var file_internal_mesh_gossip_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_mesh_gossip_proto_init() }
func file_internal_mesh_gossip_proto_init() {
	if File_internal_mesh_gossip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_mesh_gossip_proto_rawDesc), len(file_internal_mesh_gossip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_mesh_gossip_proto_goTypes,
		DependencyIndexes: file_internal_mesh_gossip_proto_depIdxs,
		MessageInfos:      file_internal_mesh_gossip_proto_msgTypes,
	}.Build()
	File_internal_mesh_gossip_proto = out.File
	file_internal_mesh_gossip_proto_goTypes = nil
	file_internal_mesh_gossip_proto_depIdxs = nil
}
